config/routes.rb
Rails.application.routes.draw do
  get 'price/index'
  get 'price/get'
  get 'welcome/index'
  resources :coins

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

app/controllers/price_controller.rb
class PriceController < ApplicationController
  #consumindo o endpoint da API de criptomoedas
  #utilizando o Resource para que não seja feito a atribuiçao imediata do JSON para economizar memoria
  def bitcoin
    url = 'https://api.coinmarketcap.com/v2/ticker/1/'
    RestClient::Resource.new(url)
  end

  def eth
    url = 'https://api.coinmarketcap.com/v2/ticker/1027/'
    RestClient::Resource.new(url)
  end

  def monero
    url = 'https://api.coinmarketcap.com/v2/ticker/328/'
    RestClient::Resource.new(url)
  end
  
  def index
    @coins = Coin.all
    #Requisitando os JSONs a partir do .get e convertendo-os para Hashes
    bit= JSON.parse(bitcoin.get)
    ethe = JSON.parse(eth.get)
    mon = JSON.parse(monero.get)
    #Atrbuindo os prices de cada em um array
    @prices = [bit["data"]["quotes"]["USD"]["price"], ethe["data"]["quotes"]["USD"]["price"], mon["data"]["quotes"]["USD"]["price"]]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #Utilizando o resource para consumir o endpoint
  def dolar
    #Pegando a data de hoje e a convertendo para colocá-la na url e assim pegar sempre a cotação mais recente
    dataHoje = Date.today.strftime("%m-%d-%Y")
    url = "https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarDia(dataCotacao=@dataCotacao)?@dataCotacao=%27#{dataHoje}%27&$top=100&$format=json"
    RestClient::Resource.new(url)
  end
  def index
    @nome = params[:nome]
    #Requisitando o JSON a partir do .get e convertendo-o para Hashe
    json = JSON.parse(dolar.get)
    @valorDol = json["value"][0]["cotacaoCompra"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def date_br(date_us)
        date_us.strftime("%d/%m/%Y")
    end

    def env_rails
        if Rails.env.development?
            "Desenvolvimento"
        elsif Rails.env.production?
            "Produção"
        else
            "Teste"
        end
    end

    def conv(req)
        JSON.parse(req)
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="field">
    <%= form.label :url_image %>
    <%= form.text_field :url_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<%= link_to "Home", root_path %>
<p id="notice"><%= notice %></p>

<h1>Coins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Acronym</th>
      <th>Url image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.id %></td>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, width: 25, height: 25 %></td>
        <td><%= link_to 'Show', coin %></td>
        <td><%= link_to 'Edit', edit_coin_path(coin) %></td>
        <td><%= link_to 'Delete', coin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coin', new_coin_path %>
<%= link_to "Preço das Moedas", price_index_path %>

app/views/coins/new.html.erb
<h1>New Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Url image:</strong>
  <%= @coin.url_image %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/price/index.html.erb
<%= link_to "Home", root_path %>
<h1>Prices</h1>
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Acronym</th>
      <th>Url image</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, width: 25, height: 25 %></td>
        <!--- Convertendo os valores para Dólar com 2 casa e utilizando os IDs para percorrer o Array --->
        <td><%= number_to_currency(@prices[coin.id - 1])  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/_menu.html.erb
<!--Criando lista de links para navegar no projeto utilizando Helper-->
<ul>
    <li>
        <%= link_to "Cadastro de Moedas", coins_path %>
    </li>
    <li>
        <%= link_to "Preço das Moedas", price_index_path %>
    </li>
</ul>

app/views/welcome/index.html.erb
<!--Utilizando variaveis de sessão e query params-->
<h1>Olá <%= @nome %>, Seja Bem vindo</h1>

<!--Convertendo o valor para a notação de Real -->
<p>O dólar hoje está valendo <%= number_to_currency(@valorDol, unit: "R$", separator: ",", delimiter: "") %>

<!--Utilizando um helper para avisar em qual enviroment o utilizador esta-->
<p>
    Você está em ambiente de <strong><%= env_rails %></strong>
</p>
<p><strong>Data:</strong> <%= date_br(Date.today) %></p>

<%= render "menu" %>